name: test magics integration

on:
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:

jobs:
  run_magics:
    name: Tests notebook magics integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-magics-runner

      - name: Install dependencies
        run: poetry install --no-interaction --with notebook -E duckdb

      - run: poetry run pytest tests/cli/test_magics.py
        name: Run tests
